name: Deploy to AWS Lambda with RDS

on:
  push:
    branches: [main]
  workflow_dispatch: # Permite ejecutar el workflow manualmente

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build TypeScript
        run: npm run build

      - name: Run database migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Prepare Lambda deployment package
        run: |
          mkdir -p lambda-package
          # Only copy necessary files
          cp -r dist package.json prisma lambda-package/

          # create .env file for lambda
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" > lambda-package/.env
          echo "PORT=8000" >> lambda-package/.env
          echo "NODE_ENV=production" >> lambda-package/.env
          echo "DB_POOL_SIZE=1" >> lambda-package/.env
          echo "DB_CONNECTION_TIMEOUT=30000" >> lambda-package/.env
          echo "DB_IDLE_TIMEOUT=10000" >> lambda-package/.env
          echo "SSL_MODE=require" >> lambda-package/.env

          cd lambda-package
          # install only production dependencies
          npm install --production
          npx prisma generate
          # delete unnecessary files
          rm -rf node_modules/typescript node_modules/@types
          # compression
          cd ..
          zip -r function.zip lambda-package/

      # FOR S3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to S3
        run: |
          aws s3 cp function.zip s3://magapp-lambda-deployments/function-${{ github.sha }}.zip

      - name: Update Lambda from S3
        run: |
          aws lambda update-function-code \
            --function-name magapp-lambda \
            --s3-bucket magapp-lambda-deployments \
            --s3-key function-${{ github.sha }}.zip \
            --publish
